import Head from "next/head";
import Image from "next/image";
import iksan from "../public/xsann.png";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin, AiFillFacebook } from "react-icons/ai";
import { useState, useContext } from "react";
import sistemPegawai from "../public/sistem pegawai.png";
import webDestinasi from "../public/web destinasi.png";
import sioktig from "../public/sioktig.png";
import idplay from "../public/idplay.png";
import design from "../public/design.png";
import code from "../public/code.png";

import Footer from "../components/Footer";
import Aboutme from "../components/Aboutme";
import PortoFolio from "../components/PortoFolio";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-bold font-poppins dark:text-white">
              iksanarifki
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer dark:text-yellow-300"
                />
              </li>
              <li>
                <a
                  href="CV.pdf"
                  download="CV Iksan Arifki.pdf"
                  // alt="alt text"
                  className="bg-gradient-to-tr from-cyan-500 to-teal-500 text-white px-4 ml-4 py-2 rounded-lg cursor-pointer font-poppins text-sm"
                  target="_blank"
                  rel="noreferrer"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-5xl text-teal-500 font-bold  py-1  ">
              Mohammad Iksan arifki
            </h2>
            <h3 className="text-2xl py-2 dark:text-white">
              Developers and Designer
            </h3>
          </div>
          <div className="flex text-5xl justify-center text-teal-500  gap-7">
            {/* <AiFillLinkedin className="cursor-pointer" /> */}
            <a
              href="https://www.linkedin.com/in/iksan-arifki/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillLinkedin className="cursor-pointer" />
            </a>
            <a
              href="https://www.facebook.com/iksanarifki27/"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillFacebook />
            </a>
            <a
              href="https://github.com/IksanArifki27"
              target="_blank"
              rel="noopener noreferrer"
            >
              <AiFillGithub />
            </a>
          </div>
          <div className="relative bg-gradient-to-tr from-teal-400 border-solid border- to-cyan-700 w-60 h-60 my-10 rounded-full overflow-hidden mx-auto ">
            <Image src={iksan} className="mt-5" width={700} />
          </div>
        </section>
        <Aboutme />
        <PortoFolio />
      </main>
      <Footer />
    </div>
  );
}
