import Head from "next/head";
import Image from "next/image";
import deved from "../public/dev-ed-wave.png";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillLinkedin, AiFillFacebook } from "react-icons/ai";
import design from "../public/design.png";
import code from "../public/code.png";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import web4 from "../public/web4.png";
import web5 from "../public/web5.png";
import web6 from "../public/web6.png";
import { useState } from "react";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>My Portofolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl font-bold font-poppins dark:text-white">
              iksanarifki
            </h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className="cursor-pointer dark:text-yellow-300"
                />
              </li>
              <li>
                <a
                  href="#"
                  className="bg-gradient-to-tr from-cyan-500 to-green-500 text-white px-4 ml-4 py-2 rounded-lg cursor-pointer text-lg"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-5">
            <h2 className="text-5xl text-teal-500 font-bold  py-1  ">
              Mohammad Iksan arifki
            </h2>
            <h3 className="text-2xl py-2 dark:text-white">
              Developers and Designer
            </h3>
            <p className="text-md py-5 leading-8 dark:text-white">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Earum,
              voluptates dolor accusantium suscipit corrupti laborum quod nam
              consequuntur soluta. Aliquid.
            </p>
          </div>
          <div className="flex text-5xl justify-center text-teal-500  gap-7">
            {/* <AiFillLinkedin className="cursor-pointer" /> */}
            <a
              href="https://www.linkedin.com/in/mohammad-iksan-arifki-695221222/"
              target={"_blank"}
            >
              <AiFillLinkedin className="cursor-pointer" />
            </a>
            <a href="https://www.facebook.com/iksanarifki27/" target={"_blank"}>
              {" "}
              <AiFillFacebook />
            </a>
            <a href="https://github.com/IksanArifki27" target={"_blank"}>
              {" "}
              <AiFillGithub />
            </a>
          </div>
          <div className="relative bg-gradient-to-tr from-teal-400 to-cyan-700 w-60 h-60 my-3 rounded-full overflow-hidden mx-auto">
            <Image src={deved} className="mt-6" />
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 font-semibold text-teal-500">
              Services I can offer
            </h3>
            <p className="text-sm text-gray-400 dark:text-white">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Assumenda
              nemo numquam consequuntur, tempora tempore ducimus quis nisi
              soluta laboriosam. Iste, quidem! Saepe repudiandae maxime a nihil
              aperiam adipisci odit beatae.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-xl rounded-md p-10 my-10  mx-auto">
              <Image
                src={design}
                width={100}
                height={100}
                className="mx-auto"
              />
              <h3 className="text-lg font-medium pt-2 pb-4 dark:text-teal-400">
                Beautiful Designs
              </h3>
              <p className="py-2">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nihil,
                eveniet!
              </p>
              <h4 className="py-2 font-medium text-teal-400">
                Design Tools Can use
              </h4>
              <p className="py-1 text-gray-800 dark:text-white">
                Adobe Photoshop
              </p>
              <p className="py-1 text-gray-800 dark:text-white">
                Adobe Ilustrator
              </p>
              <p className="py-1 text-gray-800 dark:text-white">Figma</p>
            </div>
            <div className="text-center shadow-xl rounded-md p-10 my-10 ">
              <Image src={code} width={100} height={100} className="mx-auto" />
              <h3 className="text-lg font-medium pt-2 pb-4 dark:text-teal-400">
                Code
              </h3>
              <p className="py-2">
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nihil,
                eveniet!
              </p>
              <h4 className="py-2 font-medium text-teal-400">
                Technology that I use
              </h4>

              <p className="py-1 text-gray-800 dark:text-white">
                HTML,CSS & javascript
              </p>
              <p className="py-1 text-gray-800 dark:text-white">
                Nodejs & Express js
              </p>
              <p className="py-1 text-gray-800 dark:text-white">
                ReactJs& nextJs
              </p>
              <p className="py-1 text-gray-800 dark:text-white">
                PHP & Laravel
              </p>
              <p className="py-1 text-gray-800 dark:text-white">
                Bootstrap & TailwindCSS
              </p>
              <p className="py-1 text-gray-800 dark:text-white">
                Mysql & MongoDB
              </p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 font-semibold text-teal-500">
              Portofolio
            </h3>
            <p className="text-sm text-gray-400 dark:text-gray-100">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit.
              Consectetur quae aperiam fugit eaque ex cum recusandae culpa?
              Aperiam error cum dolorum, sed quos ducimus nesciunt!
            </p>
            <p className="text-sm text-gray-400 dark:text-gray-100">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Iste
              consectetur sint quibusdam qui a tenetur dolores enim dolore
              soluta, ad nulla repellat ipsam veritatis animi sed beatae
              voluptates. Quos, doloremque.
            </p>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex lg:flex-row lg:flex-wrap ">
            <div className="flex-1 basis-1/3">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                src={web2}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                src={web3}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                src={web4}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                src={web5}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
            <div className="flex-1 basis-1/3">
              <Image
                src={web6}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
              />
            </div>
          </div>
          <div className="my-30"></div>
        </section>
      </main>
      <footer>
        <div className="bg-gray-800 lg:w-full">
          <h2 className="text-white text-center p-10">
            Create By Iksan arifki❤️
          </h2>
        </div>
      </footer>
    </div>
  );
}
